# -*- coding: utf-8 -*-
"""Chirayu.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Scz_VbcfIBJzSqk3XAJDctsDtUQiwBi1
"""

print("hello orld")

name = "Chirayu Save"

name.index("a")

name.split()

name.replace("Save", "python")

s1 = "CS"
s2 = "PY"
s1.join(s2)

len(name)

s1 = "cs"
s2 = "cs"
if(s1 == s2):
  print("Both strings are equal")