# -*- coding: utf-8 -*-
"""chirayu

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BFLYdHDl-od9aCuq6R59CkTBz81mr8r7
"""

dict = {'name': 'chirayu' , 'age': 21}
print(dict['name'])
print(dict.get('age'))

dict['address'] = 'bordi'
print(dict)

dict[4] = 2
print(dict)

squars = {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
print(squars.pop(4))
print(squars)
print(squars.popitem())
print(squars)
squars.clear()
print(squars)
del squars
print(squars)

sqares = {X: X*X for X in range(6)}
print(sqares)

odd_sqares = {X: X*X for X in range(11) if X % 2 == 1}
print(odd_sqares)

sqares = {0: 0, 1: 1, 3: 9, 5: 25, 7: 49, 9: 81}
print(all(sqares))
print(any(sqares))
print(len(sqares))
print(sorted(sqares))

