# -*- coding: utf-8 -*-
"""CS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gAtUWkbAUceUSkZ0Nqm4rFLjgtNOWLmf

Q1. use IF ELSE and ELIF to write a program in python for your report cards
"""

marks = 72

if marks >= 97:
  print("Grade -> A+")
elif marks >= 93:
  print("Grade -> A") 
elif marks >= 90:
  print("Grade -> A-") 
elif marks >= 87:
  print("Grade -> B+") 
elif marks >= 83:
  print("Grade -> B") 
elif marks >= 80:
  print("Grade -> B-") 
elif marks >= 77:
  print("Grade -> C+") 
elif marks >= 73:
  print("Grade -> C") 
elif marks >= 70:
  print("Grade -> C-") 
elif marks >= 67:
  print("Grade -> D+") 
elif marks >= 63:
  print("Grade -> D") 
elif marks >= 60:
  print("Grade -> D-") 
else:
  print("Failed")

"""Q2. Use For Loop to print prime numbers in between 1 to 1000"""

lower = int(input("Enter lower range: "))

upper = int(input("Enter upper range: "))

lower = 1
upper = 1000

print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper + 1):
  if num > 1:
    for i in range(2, num):
      if (num % i) == 0:
        break
    else:
      print(num)

"""Q3. Write a program for printing the tables from 1,10 usin nested for loop"""

for item in range(1,11):
  print(item)
  for a in range(1,11):
    print(item, "X", a, "=", item*a)

"""Q4. write a program to print X prime numbers using while loop starting from 0 and take the input from the user"""

num = int(input("Enter a number: "))
if num > 0:
   for i in range(2,num):
       if (num % i) == 0:
           print(num,"is not a prime number")
           print(i,"times",num//i,"is",num)
           break
   else:
       print(num,"is a prime number")
else:
   print(num,"is not a prime number")