# -*- coding: utf-8 -*-
"""CS4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PlITGxY8oqdsvSuQ8Fr1Xfr69q64GZaZ

Q1. Write down a program in python for opening a file and write.
"""

f = open("LetsUpgrade.txt", "w+")
f.write("I like to lern with LetsUpgreade")
f.close()

f = open("LetsUpgrade.txt","r")
content = f.read()
f.close()

content

f = open("LetsUpgrade.txt", "a+")
f.write("It was Good section")
f.close()

"""Q2. Write a function which can return a list of factorial of any numbers,given in the arrgument"""

num = 3
fact = 1
for i in range(1, num+1):
 fact = fact * i
print("The Factorial of 3 is :", end = " ")
print(fact)