# -*- coding: utf-8 -*-
"""CS5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0gPUOQa9zo2LNB5A9iCyWEVAHWGGfrX

Q1. write a python program which convert, Any given text to chiper text and when every the key is avaliable it should convert it back to the normal message.
"""

!pip install cryptography

from cryptography.fernet import Fernet

def genratePassKey():
  key = Fernet.generate_key()
  print(key)
  print(type(key))
  abc = open("PasswordKey.key", 'wb')
  abc.write(key)
  abc.close()

genratePassKey()

def getMyKey():
  abc = open("PasswordKey.key", 'rb')
  return abc.read()

getMyKey()

def getContentFromUser():
  return input("Enter the Content you want to Encrypt in your python script")

getContentFromUser()

def encryptMessage(message_normal):
  key = getMyKey()
  k = Fernet(key)
  encrypted_Message = k.encrypt(message_normal)
  return encrypted_Message

encryptMessage(b"Hey")

def decryptMessage(message_secret):
  key = getMyKey()
  k = Fernet(key)
  decrypted_Message = k.decrypt(message_secret)
  return decrypted_Message

decryptMessage(b'gAAAAABf3vTzstkVHLrko8wd14EuKaXQP3u9kO7rwPtAJnd8dUhcx2WSelZPTmqhqpxy-4HlLklx2HVaoWIJR5qP4dHnakdU4w==')

