# -*- coding: utf-8 -*-
"""cs.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYPlQcRKyky5Cwd3QQPPUkIURcmybE6N
"""

list = [1,2,3,4,5,6,"chirayu","abc"]
list.append("xyz")
print(list)

list.insert(2, 1)
print(list)

list = [1,2,3,4,5]
print(sum(list))

list = [1,3,2,4,1,1,4,2]
print(list.count(1))

lst = [1,2,3,4,5,6,7,8,9]
print(len(lst))

lst.index(2)